version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.302
    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package
      - run: cd target && ls
      